apiVersion: v1
kind: Service
metadata:
  name: sentiment-service
  labels:
    app: sentiment-analyzer-app
spec:
  type: LoadBalancer
  selector:
    app: sentiment-analyzer-app
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP